### ISSUE TITLE
In SCSS, use rem instead of px for layout-based units

### ISSUE THREAD

**Issue by Newnab** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#61]
Originally reported by @peterkeating so he can provide more context.

**Comment by peterkeating** [comment]
Searching for "padding" shows a fair few occurrences of where `padding` is defined without using rem and also when `px` values are defined in the settings instead of `rem`.

- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/components/list/_navigation.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/tools/_content.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/components/_hero.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/components/list/_settings.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/base/button/_button.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/components/section/_settings.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/components/_settings.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/components/header/_settings.scss

Same for `margin`.

- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/tools/_content.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/components/list/_settings.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/base/_blockquote.scss
- [ ] https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/blob/030a6f6d5470708dc1ee31028488fd72af1e3e72/content/Assets/Styles/components/header/_settings.scss
