### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by bengammon** [EtchUK/Etch.OrchardCore.ThemeBoilerplate#87]
I'm about to start work on implementing some responsive tables for a client project. The boilerplate doesn't yet contain any table styles (basic or responsive), so now feels like a good time to discuss what we would like our approach to be. The project work I do can then go straight into the boilerplate.

@lawrencedine, @peterkeating and @Newnab - I welcome your thoughts on the below...

### Tables or divs?

We need to make a decision on whether to stick with `<table>`'s or roll our own solution using flexbox. 

I found this excellent article that goes into lots of detail about tables, screen readers, ARIA, etc: https://adrianroselli.com/2017/11/hey-its-still-ok-to-use-tables.html

Both [gov.uk](https://design-system.service.gov.uk/components/table/) and [Bootstrap](https://getbootstrap.com/docs/4.3/content/tables/) roll tables. They also add `<caption>`'s to their tables, which help screen readers to find a table and understand what it’s about.

### Responsive tables

How should tables behave on smaller screens? 

In a previous project, we made tables horizontally scrollable. But I like the example @Newnab found, whereby each row becomes a mini table:

https://codepen.io/AllThingsSmitty/pen/MyqmdM

I think this should be our default approach to tables, but more complex data might require a different solution. The approach above also requires the use of `data-label`'s on each table cell, does anyone envisage this being a problem?

**Comment by peterkeating** [comment]
I think we should be using `table`, and the fact gov.uk & Bootstrap are using that approach reaffirms my opinion. Always think you should be using the appropriate html element when it's available instead of going with a `div` approach.

I'm also a much bigger fan of the example @Newnab has linked. When thinking about responsive tables I also like the approaches used by Filament Group - https://github.com/filamentgroup/tablesaw
